//= require 'jquery/dist/jquery.min.js'
//= require 'three.js/build/three.js'
//= require 'three.js/examples/js/controls/OrbitControls.js'
//= require 'three.js/examples/js/postprocessing/ShaderPass.js'
//= require 'three.js/examples/js/shaders/CopyShader.js'
//= require 'three.js/examples/js/postprocessing/EffectComposer.js'
//= require 'three.js/examples/js/postprocessing/MaskPass.js'
//= require 'three.js/examples/js/postprocessing/FilmPass.js'
//= require 'three.js/examples/js/shaders/FilmShader.js'
//= require 'three.js/examples/js/postprocessing/RenderPass.js'
//= require 'three.js/examples/js/postprocessing/BloomPass.js'


//= require 'three.js/examples/js/shaders/DotScreenShader.js'
//= require 'three.js/examples/js/shaders/RGBShiftShader.js'
